description = "Ubuntu bionic base image with buildpacks for Java, NodeJS and Golang"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/dotnet-core:0.0.8"
  version = "0.0.8"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/go:0.2.1"
  version = "0.2.1"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/java-native-image:3.5.0"
  version = "3.5.0"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/java:3.6.0"
  version = "3.6.0"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/nginx:0.0.193"
  version = "0.0.193"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/nodejs:0.0.9"
  version = "0.0.9"

[[buildpacks]]
  image = "gcr.io/paketo-buildpacks/procfile:2.0.3"
  version = "2.0.3"

[lifecycle]
  version = "0.9.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "3.5.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "3.6.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "0.0.9"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/go"
    version = "0.2.1"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/dotnet-core"
    version = "0.0.8"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nginx"
    version = "0.0.193"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "2.0.3"

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "docker.io/paketobuildpacks/build:0.0.95-base-cnb"
  run-image = "index.docker.io/paketobuildpacks/run:base-cnb"
  run-image-mirrors = ["gcr.io/paketo-buildpacks/run:base-cnb"]
